// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdService.Models;

namespace ProdService.Migrations
{
    [DbContext(typeof(ProdServiceContext))]
    [Migration("20220428205817_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProdService.Models.DishCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DishCarts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Сосиска отварная, каша пшеная вязкая"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Лук, хлеб ржаной"
                        });
                });

            modelBuilder.Entity("ProdService.Models.DishCartMenuItemJunction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DishCartId")
                        .HasColumnType("bigint");

                    b.Property<long>("MealId")
                        .HasColumnType("bigint");

                    b.Property<long>("MenuItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DishCartId");

                    b.HasIndex("MealId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("DishCartMenuItemJunctions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DishCartId = 1L,
                            MealId = 1L,
                            MenuItemId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DishCartId = 1L,
                            MealId = 1L,
                            MenuItemId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            DishCartId = 2L,
                            MealId = 2L,
                            MenuItemId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            DishCartId = 2L,
                            MealId = 2L,
                            MenuItemId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            DishCartId = 2L,
                            MealId = 2L,
                            MenuItemId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            DishCartId = 2L,
                            MealId = 3L,
                            MenuItemId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            DishCartId = 1L,
                            MealId = 1L,
                            MenuItemId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            DishCartId = 1L,
                            MealId = 1L,
                            MenuItemId = 2L
                        });
                });

            modelBuilder.Entity("ProdService.Models.Meal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Завтрак"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Обед"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Ужин"
                        });
                });

            modelBuilder.Entity("ProdService.Models.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Date = new DateTime(2022, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            Date = new DateTime(2022, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ProdService.Models.Processing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ReduceFats")
                        .HasColumnType("float");

                    b.Property<double>("ReduceSquirrels")
                        .HasColumnType("float");

                    b.Property<double>("ReduceСarbohydrates")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Processings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Без обработки",
                            ReduceFats = 0.0,
                            ReduceSquirrels = 0.0,
                            ReduceСarbohydrates = 0.0
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Очистка",
                            ReduceFats = 0.0,
                            ReduceSquirrels = 0.0,
                            ReduceСarbohydrates = 0.0
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Тепловая обработка",
                            ReduceFats = 0.12,
                            ReduceSquirrels = 0.059999999999999998,
                            ReduceСarbohydrates = 0.089999999999999997
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Очистка + Тепловая обработка",
                            ReduceFats = 0.12,
                            ReduceSquirrels = 0.059999999999999998,
                            ReduceСarbohydrates = 0.089999999999999997
                        });
                });

            modelBuilder.Entity("ProdService.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<double>("HeatTreatmentRate")
                        .HasColumnType("float");

                    b.Property<double>("KCal")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NormPerDay")
                        .HasColumnType("float");

                    b.Property<double>("PeelRate")
                        .HasColumnType("float");

                    b.Property<long>("ProductGroupId")
                        .HasColumnType("bigint");

                    b.Property<double>("Squirrels")
                        .HasColumnType("float");

                    b.Property<double>("Сarbohydrates")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductGroupId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Fats = 49.299999999999997,
                            HeatTreatmentRate = 0.32000000000000001,
                            KCal = 491.0,
                            Name = "Свинина",
                            NormPerDay = 150.0,
                            PeelRate = 0.245,
                            ProductGroupId = 1L,
                            Squirrels = 11.699999999999999,
                            Сarbohydrates = 0.0
                        },
                        new
                        {
                            Id = 2L,
                            Fats = 3.2999999999999998,
                            HeatTreatmentRate = 4.0,
                            KCal = 348.0,
                            Name = "Пшено",
                            NormPerDay = 100.0,
                            PeelRate = 0.0,
                            ProductGroupId = 5L,
                            Squirrels = 11.5,
                            Сarbohydrates = 66.5
                        },
                        new
                        {
                            Id = 3L,
                            Fats = 1.3999999999999999,
                            HeatTreatmentRate = 0.0,
                            KCal = 210.0,
                            Name = "Xлеб ржаной",
                            NormPerDay = 100.0,
                            PeelRate = 0.0,
                            ProductGroupId = 7L,
                            Squirrels = 7.7000000000000002,
                            Сarbohydrates = 37.600000000000001
                        },
                        new
                        {
                            Id = 4L,
                            Fats = 0.20000000000000001,
                            HeatTreatmentRate = 0.5,
                            KCal = 41.0,
                            Name = "Лук",
                            NormPerDay = 30.0,
                            PeelRate = 0.16,
                            ProductGroupId = 6L,
                            Squirrels = 1.3999999999999999,
                            Сarbohydrates = 8.1999999999999993
                        },
                        new
                        {
                            Id = 5L,
                            Fats = 31.600000000000001,
                            HeatTreatmentRate = 0.029999999999999999,
                            KCal = 270.0,
                            Name = "Сосиски",
                            NormPerDay = 100.0,
                            PeelRate = 0.029999999999999999,
                            ProductGroupId = 3L,
                            Squirrels = 10.1,
                            Сarbohydrates = 1.8999999999999999
                        },
                        new
                        {
                            Id = 6L,
                            Fats = 78.0,
                            HeatTreatmentRate = 0.0,
                            KCal = 709.0,
                            Name = "Масло сливочное",
                            NormPerDay = 30.0,
                            PeelRate = 0.0,
                            ProductGroupId = 4L,
                            Squirrels = 0.69999999999999996,
                            Сarbohydrates = 1.0
                        });
                });

            modelBuilder.Entity("ProdService.Models.ProductDishCartJunction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DishCartId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProcessingId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<double>("WeightBrutto")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DishCartId");

                    b.HasIndex("ProcessingId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDishCartJunctions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DishCartId = 1L,
                            ProcessingId = 2L,
                            ProductId = 2L,
                            WeightBrutto = 80.0
                        },
                        new
                        {
                            Id = 2L,
                            DishCartId = 1L,
                            ProcessingId = 2L,
                            ProductId = 5L,
                            WeightBrutto = 80.0
                        },
                        new
                        {
                            Id = 3L,
                            DishCartId = 1L,
                            ProcessingId = 1L,
                            ProductId = 6L,
                            WeightBrutto = 5.0
                        },
                        new
                        {
                            Id = 4L,
                            DishCartId = 2L,
                            ProcessingId = 2L,
                            ProductId = 4L,
                            WeightBrutto = 20.0
                        },
                        new
                        {
                            Id = 5L,
                            DishCartId = 2L,
                            ProcessingId = 1L,
                            ProductId = 3L,
                            WeightBrutto = 100.0
                        });
                });

            modelBuilder.Entity("ProdService.Models.ProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Мясная продукция"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Рыбная продукция"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Колбасные изделия"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Жиры"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Крупа"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Овощи"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Хлебобулочные изделия"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Консервные изделия"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Прочие"
                        });
                });

            modelBuilder.Entity("ProdService.Models.DishCartMenuItemJunction", b =>
                {
                    b.HasOne("ProdService.Models.DishCart", "DishCart")
                        .WithMany("DishCartMenuItemJunctions")
                        .HasForeignKey("DishCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProdService.Models.Meal", "Meal")
                        .WithMany("DishCartMenuItemJunctions")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProdService.Models.MenuItem", "MenuItem")
                        .WithMany("DishCartMenuItemJunctions")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DishCart");

                    b.Navigation("Meal");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("ProdService.Models.Product", b =>
                {
                    b.HasOne("ProdService.Models.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("ProdService.Models.ProductDishCartJunction", b =>
                {
                    b.HasOne("ProdService.Models.DishCart", "DishCart")
                        .WithMany("ProductDishCarts")
                        .HasForeignKey("DishCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProdService.Models.Processing", "Processing")
                        .WithMany()
                        .HasForeignKey("ProcessingId");

                    b.HasOne("ProdService.Models.Product", "Product")
                        .WithMany("ProductDishCarts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DishCart");

                    b.Navigation("Processing");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProdService.Models.DishCart", b =>
                {
                    b.Navigation("DishCartMenuItemJunctions");

                    b.Navigation("ProductDishCarts");
                });

            modelBuilder.Entity("ProdService.Models.Meal", b =>
                {
                    b.Navigation("DishCartMenuItemJunctions");
                });

            modelBuilder.Entity("ProdService.Models.MenuItem", b =>
                {
                    b.Navigation("DishCartMenuItemJunctions");
                });

            modelBuilder.Entity("ProdService.Models.Product", b =>
                {
                    b.Navigation("ProductDishCarts");
                });

            modelBuilder.Entity("ProdService.Models.ProductGroup", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
